language: php

os: linux

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL_VERSION=^5.8
  - LARAVEL_VERSION=^6

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - LARAVEL_VERSION=^5.8
        - PHPUNIT_VERSION=^7
  exclude:
    - php: 7.1
      env: LARAVEL_VERSION=^6

before_script:
  - travis_retry composer self-update
  - if [ "$LARAVEL_VERSION" !== "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - if [ "$PHPUNIT_VERSION" !== "" ]; then composer require --dev "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - travis_retry composer install --no-interaction

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls